name: Publish To Maven Central
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Maven # Maven 环境变量配置了对应密钥信息
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish package
        run: |
          echo $MAVEN_USERNAME >> secrets.txt
          echo $MAVEN_GPG_PASSPHRASE >> secrets.txt
          #mvn -P release --batch-mode deploy -DskipTests
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
